//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StoreFront.DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public int BrandID { get; set; }
        public int TypeID { get; set; }
        public int PersonalizedID { get; set; }
        public bool IsShipped { get; set; }
        public int EmployeeID { get; set; }
        public bool IsOnBackOrder { get; set; }
        public decimal UnitsSold { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public int ColorID { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual Color Color { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Personalized Personalized { get; set; }
        public virtual ProductType ProductType { get; set; }
    }
}
